/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EggPickerApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.applet.Applet;

class AppTest {
    @Test
    void appHasAGreeting() {
        Applet classUnderTest = new Applet();
    }
}
